(defun prime(N)
	(if (< N 2)
		(format t "~A is not a prime.~%" N)
		(progn
			(setq L 2)
			(setq R (floor (sqrt N)) )
			(loop (incf L)
				(when(> L R) (return (format t "~A is a prime.~%" N) ) )
				(if (= (MOD N L) 0)
					(return (format t "~A is not a prime.~%" N))
				)
			)
		)
	)
)

(terpri)
(prime 1)
(prime 2)
(prime 239)
(prime 999)
(prime 17)
